package loadbalancer

import (
	"fmt"
	"log/slog"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
)

type templateArgs struct {
	Package   golang.PackageInfo
	IfaceName string
	Name      string
	BaseType  string
	Service   *gocode.ServiceInterface
	Imports   *gogen.Imports
}

func generateLBServer(builder golang.ModuleBuilder, iface *gocode.ServiceInterface, client_iface *gocode.ServiceInterface, pkgname string) error {
	pkg, err := builder.CreatePackage(pkgname)
	if err != nil {
		return err
	}

	templ := templateArgs{
		Package:   pkg,
		IfaceName: iface.String(),
		Name:      iface.BaseName + "LoadBalancer",
		BaseType:  client_iface.String(),
		Service:   iface,
		Imports:   gogen.NewImports(pkg.Name),
	}

	templ.Imports.AddPackages("context", "sync")
	templ.Imports.AddType(&iface.UserType)
	slog.Info(fmt.Sprintf("Generating %v/%v", templ.Package.PackageName, templ.Name))
	outputFile := filepath.Join(templ.Package.Path, templ.Name+".go")
	return gogen.ExecuteTemplateToFile("LoadBalancer", lbServerTemplate, templ, outputFile)
}

var lbServerTemplate = `// Blueprint: Auto-generated by LoadBalance plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.Name}} struct {
	Clients []{{.BaseType}}
	m sync.Mutex
	idx int
	N int
}

func New{{.Name}} (ctx context.Context, clients ...{{.BaseType}}) ({{.IfaceName}}, error) {
	handler := &{{.Name}}{}
	handler.Clients = clients
	handler.N = len(clients)
	return handler, nil
}

// Round Robin policy for the load balancer
func (balancer *{{.Name}}) pickClient() ({{.BaseType}}, error) {
	balancer.m.Lock()
	defer balancer.m.Unlock()
	client := balancer.Clients[balancer.idx]
	balancer.idx = (balancer.idx + 1) % balancer.N
	return client, nil
}

{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{$bType := .BaseType}}
{{ range $_, $f := .Service.Methods }}
func (balancer *{{$receiver}}) {{$f.Name}} ({{ArgVarsAndTypes $f "ctx context.Context"}}) ({{RetVarsAndTypes $f "err error"}}) {
	// Pick the client to use
	var client {{$bType}}
	client, err = balancer.pickClient()
	if err != nil {
		return
	}
	return client.{{$f.Name}}({{ArgVars $f "ctx"}})
}
{{end}}
`
