package loadbalancer

import (
	"errors"
	"fmt"
	"log/slog"
	"strings"

	"github.com/blueprint-uservices/blueprint/blueprint/pkg/coreplugins/service"
	"github.com/blueprint-uservices/blueprint/blueprint/pkg/ir"
	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
	"github.com/blueprint-uservices/blueprint/plugins/workflow/workflowspec"
)

type dynamicLBNode struct {
	golang.Service

	InstanceName string
	TypeName     string
	ServiceType  string // The short-name serviceType that this is a load balancer for

	// Details of the service, including its interface and constructor
	ServiceInfo *workflowspec.Service
}

func (n *dynamicLBNode) Name() string {
	return n.InstanceName
}

// Both the client and the handler need to add interfaces to modules that use them.
func (n *dynamicLBNode) GetInterface(ctx ir.BuildContext) (service.ServiceInterface, error) {
	return n.ServiceInfo.Iface.ServiceInterface(ctx), nil
}

// Both the client and the handler need to add interfaces to modules that use them.
func (node *dynamicLBNode) AddInterfaces(builder golang.ModuleBuilder) error {
	return node.ServiceInfo.AddToModule(builder)
}

type dynamicLBHandler struct {
	dynamicLBNode
	golang.GeneratesFuncs

	PkgName string
	Args    []ir.IRNode
	Clients []golang.Service
}

type dynamicLBClient struct {
	dynamicLBNode

	Wrapped ir.IRNode
}

func initDynamicLBNode[ServiceType any](n *dynamicLBNode, name string) error {
	n.InstanceName = name
	var err error
	n.ServiceInfo, err = workflowspec.GetService[ServiceType]()
	if err != nil {
		return err
	}
	n.ServiceType = n.ServiceInfo.Iface.Name
	n.TypeName = n.ServiceType + "LoadBalancer"
	return nil
}

func (n *dynamicLBHandler) Init(arg_nodes []ir.IRNode) error {
	clients := []golang.Service{}
	for _, n := range arg_nodes {
		if c, ok := n.(golang.Service); ok {
			clients = append(clients, c)
		} else {
			return errors.New(fmt.Sprintf("%s is not a golang.Service node", n))
		}
	}
	n.PkgName = "lb"
	n.Args = arg_nodes
	n.Clients = clients
	return nil
}

// Override the handler functionality to add more interfaces
func (n *dynamicLBHandler) AddInterfaces(builder golang.ModuleBuilder) error {
	for _, node := range n.Args {
		if arg, valid := node.(golang.ProvidesInterface); valid {
			if err := arg.AddInterfaces(builder); err != nil {
				return err
			}
		}
	}
	return n.ServiceInfo.AddToModule(builder)
}

// Client and handler side both need to add the service interface to the output
func (node *dynamicLBNode) AddToWorkspace(builder golang.WorkspaceBuilder) error {
	return golang.AddToWorkspace(builder, node.ServiceInfo.Iface.File.Package.Module)
}

// The handler node needs to add the constructor package to the output
func (node *dynamicLBHandler) AddToWorkspace(builder golang.WorkspaceBuilder) error {
	return node.ServiceInfo.AddToWorkspace(builder)
}

func (n *dynamicLBHandler) AddInstantiation(builder golang.NamespaceBuilder) error {
	if builder.Visited(n.InstanceName) {
		return nil
	}

	constructor := &gocode.Constructor{
		Package: builder.Module().Info().Name + "/" + n.PkgName,
		Func: gocode.Func{
			Name: "New" + n.ServiceType + "LoadBalancer",
			Arguments: []gocode.Variable{
				{Name: "ctx", Type: &gocode.UserType{Package: "context", Name: "Context"}},
			},
			Returns: n.ServiceInfo.Constructor.Returns,
		},
	}

	builder.ImportType(n.ServiceInfo.Iface.Type())

	for i, arg := range n.Args {
		iface, err := golang.GetGoInterface(builder, arg)
		if err != nil {
			return err
		}
		cons_arg := gocode.Variable{Name: fmt.Sprintf("client_%d", i), Type: iface}
		constructor.Arguments = append(constructor.Arguments, cons_arg)
	}

	slog.Info(fmt.Sprintf("Instantiating %v %v in %v/%v", n.ServiceType, n.InstanceName, builder.Info().Package.PackageName, builder.Info().FileName))
	return builder.DeclareConstructor(n.InstanceName, constructor, n.Args)
}

func (node *dynamicLBHandler) GenerateFuncs(builder golang.ModuleBuilder) error {
	if builder.Visited(node.InstanceName + ".generateFuncs") {
		return nil
	}

	iface, err := golang.GetGoInterface(builder, node)
	if err != nil {
		return err
	}

	client_iface, err := golang.GetGoInterface(builder, node.Args[0])
	if err != nil {
		return err
	}

	return generateLBServer(builder, iface, client_iface, node.PkgName)

}

type lbClientTemplateArgs struct {
	ServiceType string
	WrappedName string
}

func (n *dynamicLBClient) AddInstantiation(builder golang.NamespaceBuilder) error {
	if builder.Visited(n.InstanceName) {
		return nil
	}

	template := `func(n *golang.Namespace) (any, error) {
		// Auto-generated by the golang plugin cerulean/ir_uml_component.go
		var client {{.ServiceType}}
		err := n.Get("{{.WrappedName}}", &client)
		return client, err
	}`

	templateArgs := &lbClientTemplateArgs{
		ServiceType: builder.ImportType(n.ServiceInfo.Iface.Type()),
		WrappedName: n.Wrapped.Name(),
	}

	code, err := gogen.ExecuteTemplate("dynamicWorkflowClient.AddInstantiation", template, templateArgs)
	if err != nil {
		return err
	}

	return builder.Declare(n.InstanceName, code)
}

func (n *dynamicLBClient) String() string {
	var b strings.Builder
	b.WriteString(n.InstanceName)
	b.WriteString(" = ")
	b.WriteString(n.Wrapped.Name())

	return b.String()
}

func (n *dynamicLBHandler) String() string {
	var b strings.Builder
	b.WriteString(n.InstanceName)
	b.WriteString(" = ")
	b.WriteString(n.TypeName)

	var args []string
	for _, arg := range n.Args {
		args = append(args, arg.Name())
	}

	b.WriteString("([]{")
	b.WriteString(strings.Join(args, ", "))
	b.WriteString("})")

	return b.String()
}

func (node *dynamicLBNode) ImplementsGolangNode()    {}
func (node *dynamicLBNode) ImplementsGolangService() {}
