package probabilistic

import (
	"fmt"
	"log/slog"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
)

func generateServerHandler(builder golang.ModuleBuilder, iface *gocode.ServiceInterface, wrapped_service *gocode.ServiceInterface, outputPackage string) error {
	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	server := &serverArgs{
		Package:   pkg,
		Service:   wrapped_service,
		Iface:     iface,
		Name:      wrapped_service.BaseName + "_ProbabilisticFailureHandler",
		IfaceName: iface.Name,
		Imports:   gogen.NewImports(pkg.Name),
	}

	server.Imports.AddPackages("context", "math/rand", "errors", "strconv")

	slog.Info(fmt.Sprintf("Generating %v/%v", server.Package.PackageName, iface.Name))
	outputFile := filepath.Join(server.Package.Path, iface.Name+".go")
	return gogen.ExecuteTemplateToFile("ProbabilisticFailureInjector", serverTemplate, server, outputFile)
}

type serverArgs struct {
	Package   golang.PackageInfo
	Service   *gocode.ServiceInterface
	Iface     *gocode.ServiceInterface
	Name      string
	IfaceName string
	Imports   *gogen.Imports
}

var serverTemplate = `// Blueprint: Auto-generated by the FaultInjector/probabilistic Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.IfaceName}} interface {
	{{range $_, $f := .Iface.Methods -}}
	{{Signature $f}}
	{{end}}
}

type {{.Name}} struct {
	Service {{.Imports.NameOf .Service.UserType}}
	Probability int
}

func New_{{.Name}}(ctx context.Context, service {{.Imports.NameOf .Service.UserType}}, probability string) (*{{.Name}}, error) {
	prob_val, err := strconv.ParseInt(probability, 10, 64)
	if err != nil {
		return nil, err
	}
	handler := &{{.Name}}{}
	handler.Service = service
	handler.Probability = int(prob_val)
	return handler, nil
}

{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{ range $_, $f := .Service.Methods }}
func (handler *{{$receiver}}) {{$f.Name -}} ({{ArgVarsAndTypes $f "ctx context.Context"}}) ({{RetVarsAndTypes $f "err error"}}) {
	val := int(rand.Int31n(100))
	if val < handler.Probability {
		err = errors.New("Artificially induced failure from the probabilistic failure plugin")
		return
	}
	return handler.Service.{{$f.Name}}({{ArgVars $f "ctx"}})
}
{{end}}
`
