package retries

import (
	"fmt"
	"path/filepath"

	"github.com/blueprint-uservices/blueprint/plugins/golang"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gocode"
	"github.com/blueprint-uservices/blueprint/plugins/golang/gogen"
	"golang.org/x/exp/slog"
)

// code generation function called from the ir.go file.
func generateClient(builder golang.ModuleBuilder, wrapped *gocode.ServiceInterface, outputPackage string, Max int64) error {
	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	client := clientArgs{
		Package: pkg,
		Service: wrapped,
		Name:    wrapped.BaseName + "_RetrierClient",
		Max:     Max,
		Imports: gogen.NewImports(pkg.Name),
	}

	client.Imports.AddPackages("context")

	return generateClientCommon(&client, clientTemplate)
}

func generateExpBackoffClient(builder golang.ModuleBuilder, wrapped *gocode.ServiceInterface, outputPackage string, delay string, limit string) error {
	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	client := clientArgs{
		Package: pkg,
		Service: wrapped,
		Name:    wrapped.BaseName + "_RetrierExpBackoffClient",
		Imports: gogen.NewImports(pkg.Name),
		Delay:   delay,
		Limit:   limit,
	}

	client.Imports.AddPackages("context", "time")

	return generateClientCommon(&client, clientExponentialBackoffTemplate)
}

func generateFixedDelayClient(builder golang.ModuleBuilder, wrapped *gocode.ServiceInterface, outputPackage string, max_tries int64, delay string) error {
	pkg, err := builder.CreatePackage(outputPackage)
	if err != nil {
		return err
	}

	client := clientArgs{
		Package: pkg,
		Service: wrapped,
		Name:    wrapped.BaseName + "_RetrierFixedDelayClient",
		Imports: gogen.NewImports(pkg.Name),
		Delay:   delay,
		Max:     max_tries,
	}

	client.Imports.AddPackages("context", "time")

	return generateClientCommon(&client, clientFixedDelayTemplate)
}

func generateClientCommon(client *clientArgs, clientTemplate string) error {
	clientName := client.Name
	slog.Info(fmt.Sprintf("Generating %v/%v", client.Package.PackageName, clientName))
	outputFile := filepath.Join(client.Package.Path, clientName+".go")
	return gogen.ExecuteTemplateToFile("Retries", clientTemplate, client, outputFile)
}

type clientArgs struct {
	Package golang.PackageInfo
	Service *gocode.ServiceInterface
	Name    string
	Max     int64
	Delay   string
	Limit   string
	Imports *gogen.Imports
}

var clientTemplate = `// Blueprint: Auto-generated by Retries Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.Name}} struct {
	Client {{.Imports.NameOf .Service.UserType}}
	MaxTries int
}

func New_{{.Name}} (ctx context.Context, client {{.Imports.NameOf .Service.UserType}}) (*{{.Name}}, error) {
	handler := &{{.Name}}{}
	handler.Client = client
	handler.MaxTries = {{.Max}}
	return handler, nil
}

{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{ range $_, $f := .Service.Methods }}
func (client *{{$receiver}}) {{$f.Name -}} ({{ArgVarsAndTypes $f "ctx context.Context"}}) ({{RetVarsAndTypes $f "err error"}}) {
	for i := 0; i < client.MaxTries; i++ {
		{{RetVars $f "err"}} = client.Client.{{$f.Name}}({{ArgVars $f "ctx"}})
		if err == nil {
			return
		}
	}
	return
}
{{end}}
`

var clientFixedDelayTemplate = `// Blueprint: Auto-generated by Retries Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.Name}} struct {
	Client {{.Imports.NameOf .Service.UserType}}
	MaxTries int
	Delay time.Duration
}

func New_{{.Name}} (ctx context.Context, client {{.Imports.NameOf .Service.UserType}}) (*{{.Name}}, error) {
	handler := &{{.Name}}{}
	handler.Client = client
	handler.MaxTries = {{.Max}}
	dur := "{{.Delay}}"
	parsed_dur, err := time.ParseDuration(dur)
	if err != nil {
		return nil, err
	}
	handler.Delay = parsed_dur
	return handler, nil
}

{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{ range $_, $f := .Service.Methods }}
func (client *{{$receiver}}) {{$f.Name -}} ({{ArgVarsAndTypes $f "ctx context.Context"}}) ({{RetVarsAndTypes $f "err error"}}) {
	for i := 0; i < client.MaxTries; i++ {
		{{RetVars $f "err"}} = client.Client.{{$f.Name}}({{ArgVars $f "ctx"}})
		if err == nil {
			return
		}
		time.Sleep(client.Delay)
	}
	return
}
{{end}}
`

var clientExponentialBackoffTemplate = `// Blueprint: Auto-generated by Retries Plugin
package {{.Package.ShortName}}

{{.Imports}}

type {{.Name}} struct {
	Client {{.Imports.NameOf .Service.UserType}}
	Delay time.Duration
	Limit time.Duration
}

func New_{{.Name}} (ctx context.Context, client {{.Imports.NameOf .Service.UserType}}) (*{{.Name}}, error) {
	handler := &{{.Name}}{}
	handler.Client = client
	parsed_delay, err := time.ParseDuration("{{.Delay}}")
	if err != nil {
		return nil, err
	}
	handler.Delay = parsed_delay
	parsed_limit, err := time.ParseDuration("{{.Limit}}")
	if err != nil {
		return nil, err
	}
	handler.Limit = parsed_limit
	return handler, nil
}

{{$service := .Service.Name -}}
{{$receiver := .Name -}}
{{ range $_, $f := .Service.Methods }}
func (client *{{$receiver}}) {{$f.Name -}} ({{ArgVarsAndTypes $f "ctx context.Context"}}) ({{RetVarsAndTypes $f "err error"}}) {
	delay := client.Delay
	i := 1
	for delay < client.Limit {
		{{RetVars $f "err"}} = client.Client.{{$f.Name}}({{ArgVars $f "ctx"}})
		if err == nil {
			return
		}
		i += 1
		time.Sleep(delay)
		delay = 2 * delay
	}
	return
}
{{end}}
`
