// Code generated by "stringer -type=Type"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BASIC-0]
	_ = x[POINTER-1]
	_ = x[LIST-2]
	_ = x[MAP-3]
	_ = x[ELLIPSIS-4]
	_ = x[USERDEFINED-5]
	_ = x[CHAN-6]
	_ = x[FUNC-7]
}

const _Type_name = "BASICPOINTERLISTMAPELLIPSISUSERDEFINEDCHANFUNC"

var _Type_index = [...]uint8{0, 5, 12, 16, 19, 27, 38, 42, 46}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
