package goproc

import (
	"fmt"
	"path/filepath"
	"strings"

	"gitlab.mpi-sws.org/cld/blueprint/blueprint/pkg/blueprint"
	"gitlab.mpi-sws.org/cld/blueprint/plugins/golang"
	"gitlab.mpi-sws.org/cld/blueprint/plugins/golang/gogen"
	"gitlab.mpi-sws.org/cld/blueprint/plugins/process"
	"golang.org/x/exp/slog"
	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

/*
golang.Process is a node that represents a runnable Golang process.  It can contain any number of
other golang.Node IRNodes.  When it's compiled, the golang.Process will generate a go module with
a runnable main method that instantiates and initializes the contained go nodes.  To achieve this,
the golang.Process also collects module dependencies from its contained nodes.

The `GenerateArtifacts` method generates the main method based on the process's contained nodes.

Most of the heavy lifting of code generation is done by the following:
* gogen/workspacebuilder
* gogen/modulebuilder
* gogen/graphbuilder

*/

var generatedModulePrefix = "blueprint/goproc"

// An IRNode representing a golang process.
// This is Blueprint's main implementation of Golang processes
type Process struct {
	blueprint.IRNode
	process.Node
	process.ProvidesProcessArtifacts
	process.InstantiableProcess

	InstanceName   string
	ArgNodes       []blueprint.IRNode
	ContainedNodes []blueprint.IRNode
}

// A Golang Process Node can either be given the child nodes ahead of time, or they can be added using AddArtifactNode / AddCodeNode
func newGolangProcessNode(name string) *Process {
	node := Process{}
	node.InstanceName = name
	return &node
}

func (node *Process) Name() string {
	return node.InstanceName
}

func (node *Process) String() string {
	var b strings.Builder
	b.WriteString(node.InstanceName)
	b.WriteString(" = GolangProcessNode(")
	var args []string
	for _, arg := range node.ArgNodes {
		args = append(args, arg.Name())
	}
	b.WriteString(strings.Join(args, ", "))
	b.WriteString(") {\n")
	var children []string
	for _, child := range node.ContainedNodes {
		children = append(children, child.String())
	}
	b.WriteString(blueprint.Indent(strings.Join(children, "\n"), 2))
	b.WriteString("\n}")
	return b.String()
}

func (node *Process) AddArg(argnode blueprint.IRNode) {
	node.ArgNodes = append(node.ArgNodes, argnode)
}

func (node *Process) AddChild(child blueprint.IRNode) error {
	node.ContainedNodes = append(node.ContainedNodes, child)
	return nil
}

type mainArg struct {
	Name string
	Doc  string
	Var  string
}

type mainTemplateArgs struct {
	Name             string
	GraphPackage     string
	GraphConstructor string
	Args             []mainArg
	Instantiate      []string
}

var mainTemplate = `// This file is auto-generated by the Blueprint goproc plugin
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"os/signal"
	"strings"

	"{{.GraphPackage}}"
	"golang.org/x/exp/slog"
)

var missingArgs []string
func checkArg(name, value string) {
	if value == "" {
		missingArgs = append(missingArgs, name)
	} else {
		slog.Info(fmt.Sprintf("%v = %v", name, value))
	}
}

func main() {
	slog.Info("Running {{.Name}}")
	{{- range $i, $arg := .Args}}
	{{$arg.Var}} := flag.String("{{$arg.Name}}", "", "Argument automatically generated from Blueprint IR: {{$arg.Doc}}")
	{{end}}

	flag.Parse()

	{{range $i, $arg := .Args -}}
	checkArg("{{$arg.Name}}", *{{$arg.Var}})
	{{end}}
	if len(missingArgs) > 0 {
		slog.Error(fmt.Sprintf("Missing required arguments: \n  %v", strings.Join(missingArgs, "\n  ")))
		os.Exit(1)
	}
	
	graphArgs := map[string]string{
		{{- range $i, $arg := .Args}}
		"{{$arg.Name}}": *{{$arg.Var}},
		{{- end}}
	}

	ctx, cancel := context.WithCancel(context.Background())
	graph, err := {{.GraphConstructor}}(ctx, cancel, graphArgs, nil, "{{.Name}}")
	if err != nil {
		slog.Error(err.Error())
		return
	}

	var node any
	{{range $i, $node := .Instantiate -}}
	if err = graph.Get("{{$node}}", &node); err != nil {
		slog.Error(err.Error())
		os.Exit(1)
	}
	{{end}}
	
	signals := make(chan os.Signal, 1)
	signal.Notify(signals, os.Interrupt)
	go func() {
		for sig := range signals {
			slog.Info(fmt.Sprintf("{{.Name}} received %v\n", sig))
			cancel()
		}
	}()

	graph.WaitGroup().Wait()

	slog.Info("{{.Name}} exiting")
}`

func (node *Process) AddProcessArtifacts(builder process.WorkspaceBuilder) error {
	if builder.Visited(node.Name()) {
		return nil
	}

	// Create the workspace dir
	procName := blueprint.CleanName(node.Name())
	outputDir, err := builder.CreateProcessDir(procName)
	if err != nil {
		return err
	}

	workspaceDir := filepath.Join(outputDir, procName)
	slog.Info(fmt.Sprintf("Building goproc %s to %s", node.Name(), workspaceDir))
	workspace, err := gogen.NewWorkspaceBuilder(workspaceDir)
	if err != nil {
		return err
	}

	// Add relevant nodes to the workspace
	for _, node := range node.ContainedNodes {
		if n, valid := node.(golang.ProvidesModule); valid {
			if err := n.AddToWorkspace(workspace); err != nil {
				return err
			}
		}
	}

	// Create the module
	moduleName := generatedModulePrefix + "/" + procName
	slog.Info(fmt.Sprintf("Creating module %v", moduleName))
	module, err := gogen.NewModuleBuilder(workspace, moduleName)
	if err != nil {
		return err
	}

	// Add and/or generate interfaces
	for _, node := range node.ContainedNodes {
		if n, valid := node.(golang.ProvidesInterface); valid {
			if err := n.AddInterfaces(module); err != nil {
				return err
			}
		}
	}

	// Generate constructors and function declarations
	for _, node := range node.ContainedNodes {
		if n, valid := node.(golang.GeneratesFuncs); valid {
			if err := n.GenerateFuncs(module); err != nil {
				return err
			}
		}
	}

	// Create the method to instantiate the graph
	graphFileName := strings.ToLower(procName) + ".go"
	procPackage := "goproc"
	constructorName := "New" + cases.Title(language.BritishEnglish).String(procName)
	graph, err := gogen.NewGraphBuilder(module, graphFileName, procPackage, constructorName)
	if err != nil {
		return err
	}

	// Add constructor invocations
	for _, node := range node.ContainedNodes {
		if n, valid := node.(golang.Instantiable); valid {
			if err := n.AddInstantiation(graph); err != nil {
				return err
			}
		}
	}

	// Generate the graph code
	if err = graph.Build(); err != nil {
		return err
	}

	// Generate the main.go
	mainArgs := mainTemplateArgs{
		Name:             node.Name(),
		GraphPackage:     fmt.Sprintf("%s/%s", module.Name, procPackage),
		GraphConstructor: fmt.Sprintf("%s.%s", procPackage, constructorName),
		Args:             nil,
		Instantiate:      nil,
	}
	for _, arg := range node.ArgNodes {
		mainArgs.Args = append(mainArgs.Args, mainArg{
			Name: arg.Name(),
			Doc:  arg.String(),
			Var:  blueprint.CleanName(arg.Name()),
		})
	}
	// For now explicitly instantiate every child node
	for _, child := range node.ContainedNodes {
		if _, isInstantiable := child.(golang.Instantiable); isInstantiable {
			mainArgs.Instantiate = append(mainArgs.Instantiate, child.Name())
		}
	}

	slog.Info(fmt.Sprintf("Generating %v/main.go", module.Name))
	mainFileName := filepath.Join(module.ModuleDir, "main.go")
	err = gogen.ExecuteTemplateToFile("goprocMain", mainTemplate, mainArgs, mainFileName)
	if err != nil {
		return err
	}

	err = workspace.Finish()
	if err != nil {
		return err
	}

	return nil
}

func (node *Process) AddProcessInstance(builder process.GraphBuilder) error {
	if builder.Visited(node.InstanceName) {
		return nil
	}

	// TODO: add cmd args
	// go run proc/module/main.go --argnamenormal=$ARG_NAME_CLEAN
	// builder.DeclareCommand()

	return nil
}
