// Code generated by "stringer -type=BasicType"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[INT64-0]
	_ = x[BOOL-1]
	_ = x[DOUBLE-2]
	_ = x[STRING-3]
	_ = x[INTERFACE-4]
	_ = x[CONTEXT-5]
	_ = x[ERROR-6]
}

const _BasicType_name = "INT64BOOLDOUBLESTRINGINTERFACECONTEXTERROR"

var _BasicType_index = [...]uint8{0, 5, 9, 15, 21, 30, 37, 42}

func (i BasicType) String() string {
	if i < 0 || i >= BasicType(len(_BasicType_index)-1) {
		return "BasicType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BasicType_name[_BasicType_index[i]:_BasicType_index[i+1]]
}
